version: '3' 
services:
  web:
    #command: ["./code/wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "code/docker_quickstart.py"]
    environment:
      - PYTHONUNBUFFERED=0
      - INSTAPY_WORKSPACE=/code
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - selenium
    volumes:
      - ./:/code
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    ports:
      - "5900:5900"
    shm_size: 128M
