version: '3'
services:
  web:
    command: ["./wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "docker_quickstart.py"]
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - selenium
    env_file: 
      - .env
    volumes:
      - ./logs:/code/logs
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    ports:
      - "5900:5900"
    shm_size: 128M
